import { ArrowRight, Check, ChevronRight, RotateCcw, Sparkles, Target, X, Zap } from "lucide-react";
import { formatEngineScore } from "./analysisEngine";

function EvaluationChart({ rows, selected }) {
  const values = [rows[0]?.beforeScore.whiteCp || 0, ...rows.map((row) => row.afterScore.whiteCp)];
  const x = (index) => 24 + index / Math.max(1, values.length - 1) * 652;
  const y = (score) => 76 - Math.tanh(score / 300) * 57;
  const points = values.map((score, index) => `${x(index)},${y(score)}`).join(" ");
  const selectedScore = values[Math.min(selected + 1, values.length - 1)] || 0;
  return <div className="analysis-chart"><div><strong>Evaluation journey</strong><span>Above center favors White · below favors Black</span></div><svg viewBox="0 0 700 150" preserveAspectRatio="none" role="img" aria-label="Engine evaluation after each move"><line x1="24" x2="676" y1="76" y2="76" /><polyline points={points} /><circle cx={x(Math.min(selected + 1, values.length - 1))} cy={y(selectedScore)} r="5" /></svg><div className="analysis-chart-labels"><span>Start</span><span>{rows.length} {rows.length === 1 ? "move" : "moves"} reviewed</span></div></div>;
}

export default function EngineReport({ state, selected, onSelect, onClose, onCancel, onRetry, openingName, playerSide }) {
  const { status, progress, rows = [], result, error } = state;
  const current = rows[selected] || rows.at(-1);
  const playerName = playerSide === "w" ? "White" : "Black";
  const material = result?.material || 0;
  return <div className="analysis-overlay" role="dialog" aria-modal="true" aria-label="Practice engine analysis">
    <section className="analysis-panel">
      <header className="analysis-header"><div className="analysis-mark"><Zap size={23} /></div><div><span className="eyebrow">STOCKFISH 19 LITE · LOCAL ANALYSIS</span><h2>Practice review</h2><p>{openingName} · Playing as {playerName}</p></div><button className="analysis-close" aria-label="Close analysis" onClick={onClose}><X size={20} /></button></header>
      {status === "running" && <div className="analysis-loading"><div className="analysis-loading-icon"><Sparkles size={28} /></div><h3>Finding the moments that matter.</h3><p>Stockfish is reviewing each position on your device. You can stop the analysis at any time.</p><div className="analysis-progress"><span style={{ width: `${progress.total ? progress.done / progress.total * 100 : 3}%` }} /></div><small>{progress.done} of {progress.total} moves reviewed</small><button onClick={onCancel}>Stop analysis</button></div>}
      {(status === "error" || status === "cancelled") && <div className="analysis-empty"><Target size={29} /><h3>{status === "cancelled" ? "Analysis stopped." : "The engine could not finish."}</h3><p>{error || "Your practice moves are still here. Start a fresh review when ready."}</p><button onClick={onRetry}><RotateCcw size={15} /> Try again</button></div>}
      {status === "ready" && result && <div className="analysis-body">
        <div className="analysis-summary"><div className="analysis-summary-lead"><span className="eyebrow dark">YOUR ENGINE SNAPSHOT</span><h3>{result.quality >= 85 ? "A confident line." : result.quality >= 65 ? "A solid base to build on." : "A useful position to revisit."}</h3><p>Estimated move quality from your moves in this practice run. Scores are based on a quick local search and can change with deeper analysis.</p></div><div className="analysis-metrics"><div><span>MOVE QUALITY</span><strong>{result.quality}<small>/100</small></strong></div><div><span>AVG. LOSS</span><strong>{result.avgLoss}<small> cp</small></strong></div><div><span>BEST MOVES</span><strong>{result.bestCount}</strong></div><div><span>KEY MOMENTS</span><strong>{result.sharpMoments}</strong></div></div></div>
        <div className="analysis-insights"><div><span><Target size={18} /></span><div><small>COACH FOCUS</small><strong>{result.biggestMiss?.loss >= 80 ? `Revisit move ${Math.floor(result.biggestMiss.index / 2) + 1}${result.biggestMiss.color === "w" ? "." : "..."} ${result.biggestMiss.san}` : "Keep your best ideas"}</strong><p>{result.biggestMiss?.loss >= 80 ? `The engine preferred ${result.biggestMiss.bestMove || "a different continuation"}. Replay this position and compare the plans.` : "No large evaluation drops appeared in your moves at this search depth. Try the same line from memory."}</p></div></div><div><span><Check size={18} /></span><div><small>FINAL POSITION</small><strong>{formatEngineScore(result.finalScore)} · {material > 0 ? `White +${material}` : material < 0 ? `Black +${Math.abs(material)}` : "Equal material"}</strong><p>Evaluation is from White's view. Material counts pawns as 1, minor pieces as 3, rooks as 5, and queens as 9.</p></div></div></div>
        <EvaluationChart rows={rows} selected={selected} />
        <div className="analysis-review"><div className="analysis-move-list"><div><span className="eyebrow dark">MOVE BY MOVE</span><h3>Your decision trail</h3></div>{rows.map((row, index) => <button key={`${row.index}-${row.san}`} className={`${index === selected ? "active" : ""} quality-${row.label.toLowerCase()}`} onClick={() => onSelect(index)}><span className="analysis-move-number">{Math.floor(row.index / 2) + 1}{row.color === "w" ? "." : "..."}</span><strong>{row.san}</strong><em>{row.label}</em><ChevronRight size={14} /></button>)}</div><div className="analysis-move-detail"><span className="eyebrow dark">POSITION REVIEW</span><h3>{current ? `Move ${Math.floor(current.index / 2) + 1}${current.color === "w" ? "." : "..."} ${current.san}` : "Select a move"}</h3>{current && <><div className="analysis-detail-tags"><span className={`quality-${current.label.toLowerCase()}`}>{current.label}</span><span>{current.phase}</span><span>{current.loss} cp lost</span></div><div className="analysis-eval-shift"><div><small>BEFORE</small><strong>{formatEngineScore(current.beforeScore)}</strong></div><ArrowRight size={17} /><div><small>AFTER</small><strong>{formatEngineScore(current.afterScore)}</strong></div></div><div className="analysis-best-line"><small>ENGINE CHOICE</small><strong>{current.bestMove || "No legal reply"}</strong><p>{current.engineLine || "The position has reached a game ending."}</p></div><p className="analysis-detail-note">{current.label === "Best" ? "You found the engine's first choice." : current.loss >= 150 ? "Try this position again and compare your move with the engine's continuation." : "Your move kept the position close to the engine's preferred plan."}</p></>}</div></div>
        <footer className="analysis-footer"><span>Powered by <a href="https://github.com/nmrugg/stockfish.js" target="_blank" rel="noreferrer">Stockfish.js</a> · local depth up to {result.depth}</span><button onClick={onRetry}><RotateCcw size={14} /> Analyze again</button></footer>
      </div>}
    </section>
  </div>;
}
