import { ArrowRight, Check, ChevronRight, RotateCcw, Sparkles, Target, X, Zap } from "lucide-react";
import { EvaluationTimeline, MaterialTimeline, QualityMix } from "./AnalysisCharts";
import { formatEngineScore } from "./analysisEngine";

export default function EngineReport({ state, selected, onSelect, onClose, onCancel, onRetry, onOpenLive, renderPosition, openingName, playerSide }) {
  const { status, progress, rows = [], result, error } = state;
  const current = rows[selected] || rows.at(-1);
  const playerName = playerSide === "w" ? "White" : "Black";
  const material = result?.material || 0;
  const labels = rows.map((row) => `${Math.floor(row.index / 2) + 1}${row.color === "w" ? "." : "..."} ${row.san}`);
  const evaluationPoints = rows.length ? [{ label: "Start", value: rows[0].beforeScore.whiteCp }, ...rows.map((row, index) => ({ label: labels[index], value: row.afterScore.whiteCp }))] : [];
  const materialPoints = rows.length ? [{ label: "Start", value: result?.initialMaterial || 0 }, ...rows.map((row, index) => ({ label: labels[index], value: row.material }))] : [];

  return <div className="analysis-overlay" role="dialog" aria-modal="true" aria-label="Practice engine analysis">
    <section className="analysis-panel">
      <header className="analysis-header"><div className="analysis-mark"><Zap size={23}/></div><div><span className="eyebrow">STOCKFISH 19 LITE · LOCAL ANALYSIS</span><h2>Practice review</h2><p>{openingName} · Playing as {playerName}</p></div><button className="analysis-close" aria-label="Close analysis" onClick={onClose}><X size={20}/></button></header>
      {status === "running" && <div className="analysis-loading"><div className="analysis-loading-icon"><Sparkles size={28}/></div><h3>Finding the moments that matter.</h3><p>Stockfish is reviewing each position on your device. You can stop the analysis at any time.</p><div className="analysis-progress"><span style={{ width: `${progress.total ? progress.done / progress.total * 100 : 3}%` }}/></div><small>{progress.done} of {progress.total} moves reviewed</small><button onClick={onCancel}>Stop analysis</button></div>}
      {(status === "error" || status === "cancelled") && <div className="analysis-empty"><Target size={29}/><h3>{status === "cancelled" ? "Analysis stopped." : "The engine could not finish."}</h3><p>{error || "Your practice moves are still here. Start a fresh review when ready."}</p><button onClick={onRetry}><RotateCcw size={15}/> Try again</button></div>}
      {status === "ready" && result && <div className="analysis-body">
        <div className="analysis-summary"><div className="analysis-summary-lead"><span className="eyebrow dark">YOUR ENGINE SNAPSHOT</span><h3>{result.quality >= 85 ? "A confident line." : result.quality >= 65 ? "A solid base to build on." : "A useful position to revisit."}</h3><p>Estimated move quality from your moves in this practice run. Scores are based on a quick local search and can change with deeper analysis.</p></div><div className="analysis-metrics"><div><span>MOVE QUALITY</span><strong>{result.quality}<small>/100</small></strong></div><div><span>AVG. LOSS</span><strong>{result.avgLoss}<small> cp</small></strong></div><div><span>BEST MOVES</span><strong>{result.bestCount}</strong></div><div><span>KEY MOMENTS</span><strong>{result.sharpMoments}</strong></div></div></div>
        <div className="analysis-insights"><div><span><Target size={18}/></span><div><small>COACH FOCUS</small><strong>{result.biggestMiss?.loss >= 80 ? `Revisit move ${Math.floor(result.biggestMiss.index / 2) + 1}${result.biggestMiss.color === "w" ? "." : "..."} ${result.biggestMiss.san}` : "Keep your best ideas"}</strong><p>{result.biggestMiss?.loss >= 80 ? `The engine preferred ${result.biggestMiss.bestMove || "a different continuation"}. Replay this position and compare the plans.` : "No large evaluation drops appeared in your moves at this search depth. Try the same line from memory."}</p></div></div><div><span><Check size={18}/></span><div><small>FINAL POSITION</small><strong>{formatEngineScore(result.finalScore)} · {material > 0 ? `White +${material}` : material < 0 ? `Black +${Math.abs(material)}` : "Equal material"}</strong><p>{result.captures} {result.captures === 1 ? "capture" : "captures"} · {result.checks} {result.checks === 1 ? "check" : "checks"} · Evaluation is from White’s view.</p></div></div></div>
        <div className="analysis-chart-grid"><EvaluationTimeline points={evaluationPoints} selected={selected + 1} onSelect={(index) => onSelect(Math.max(0, index - 1))}/><MaterialTimeline points={materialPoints} selected={selected + 1} onSelect={(index) => onSelect(Math.max(0, index - 1))}/></div>
        <div className="analysis-data-grid"><QualityMix counts={result.classification}/><div className="analysis-phase-card"><div><small>TRAINING PHASES</small><strong>Where time was lost</strong></div>{result.phaseSummary.map((item) => <div className="analysis-phase-row" key={item.phase}><span>{item.phase}</span><div><i style={{ width: `${item.count ? Math.max(5, Math.min(100, item.avgLoss / 3)) : 0}%` }}/></div><strong>{item.count ? `${item.avgLoss} cp` : "—"}</strong></div>)}<p>Average centipawns lost per move you played in each phase.</p></div></div>
        <div className="analysis-review"><div className="analysis-move-list"><div><span className="eyebrow dark">MOVE BY MOVE</span><h3>Your decision trail</h3></div>{rows.map((row, index) => <button key={`${row.index}-${row.san}`} className={`${index === selected ? "active" : ""} quality-${row.label.toLowerCase()}`} onClick={() => onSelect(index)}><span className="analysis-move-number">{Math.floor(row.index / 2) + 1}{row.color === "w" ? "." : "..."}</span><strong>{row.san}</strong><em>{row.label}</em><ChevronRight size={14}/></button>)}</div><div className="analysis-move-detail"><span className="eyebrow dark">POSITION REVIEW</span><h3>{current ? `Move ${Math.floor(current.index / 2) + 1}${current.color === "w" ? "." : "..."} ${current.san}` : "Select a move"}</h3>{current && <><div className="analysis-detail-layout"><div><div className="analysis-detail-tags"><span className={`quality-${current.label.toLowerCase()}`}>{current.label}</span><span>{current.phase}</span><span>{current.loss} cp lost</span></div><div className="analysis-eval-shift"><div><small>BEFORE</small><strong>{formatEngineScore(current.beforeScore)}</strong></div><ArrowRight size={17}/><div><small>AFTER</small><strong>{formatEngineScore(current.afterScore)}</strong></div></div><div className="analysis-best-line"><small>ENGINE CHOICE</small><strong>{current.bestMove || "No legal reply"}</strong><p>{current.engineLine || "The position has reached a game ending."}</p></div><p className="analysis-detail-note">{current.label === "Best" ? "You found the engine’s first choice." : current.loss >= 150 ? "Try this position again and compare your move with the engine’s continuation." : "Your move kept the position close to the engine’s preferred plan."}</p></div><div className="analysis-mini-board">{renderPosition(current.fenAfter)}<span>Position after {current.san}</span></div></div></>}</div></div>
        <footer className="analysis-footer"><span>Powered by <a href="https://github.com/nmrugg/stockfish.js" target="_blank" rel="noreferrer">Stockfish.js</a> · local depth up to {result.depth}</span><div><button onClick={onRetry}><RotateCcw size={14}/> Analyze again</button><button className="analysis-open-live" onClick={onOpenLive}><Zap size={14}/> Open in Live Analysis <ArrowRight size={14}/></button></div></footer>
      </div>}
    </section>
  </div>;
}
